[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
strict = false

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = "."
testpaths = ["tests"]
