name: CI

on:
  pull_request:

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: pip install flake8 mypy pytest
      - run: flake8 bus_server.py kb.py agent_server.py tests
      - run: mypy bus_server.py kb.py agent_server.py tests
      - run: pytest
